### PR TITLE
Sets declaration as statements

### PR DESCRIPTION
**Pull request by bloody76**
This change is [Reviewable](https://reviewable.io/reviews/nitnelave/hopper/47)

### CODE REVIEW

**Comment by nitnelave** [comment]
add pretty-printer tests

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/47#-:-KqrYir6lBjYgkHhF-z5:bn08cko)*

**Comment by bloody76** [comment]
Pretty printer tests added, was worth it in the end because there was an issue with the printing of function declarations.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/47#-:-Kqvr1fGyKRH7tAiyIKp:b1cfptg)*

**Comment by nitnelave** [comment]
I noticed the bug on pretty printing, it's also fixed in my PR (typechecking) because it broke some tests. Can you export it to a new PR that I would quick-LGTM?

---

Review status: 3 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/47#-:-KqvtW986DtGvi1rsV1B:b5iq1ja)*

**Comment by bloody76** [comment]
Ok will do.

---

Review status: 3 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/47#-:-KqvxIIjmgEOGVmb2hb5:b2kjol0)*

**Comment by nitnelave** [comment]
:lgtm:

---

Review status: 2 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/47#-:-KrFN_Tr6EkvsPKEPjZ_:bnfp4nl)*

**Pull request merged**
