### PR TITLE
Add logging and improve flags

### PR DESCRIPTION
**Pull request by nitnelave**
This PR adds a logging utility to facilitate development.

---
This change is [Reviewable](https://reviewable.io/reviews/nitnelave/hopper/41)

### CODE REVIEW

**Comment by bloody76** [comment]
Reviewed 3 of 3 files at r1.
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/util/logging.cc, line 9 at r1](https://reviewable.io:443/reviews/nitnelave/hopper/41#-Kqh8gom64XmESyWuZZv:-Kqh8gom64XmESyWuZZw:b-ylp9yi) ([raw file](https://github.com/nitnelave/hopper/blob/2dbd4e7351e1ce89eb2b44a44f36f4e943d89c31/src/util/logging.cc#L9)):*
> ```cpp
> 
> // log(INFO) << "Just a joke";
> // log_if(INFO, a > 3) << "Nothing much";
> ```

dead code or example?

---

*[src/util/logging.h, line 9 at r1](https://reviewable.io:443/reviews/nitnelave/hopper/41#-Kqh8mILo9oXwRAH5-Fx:-Kqh8mILo9oXwRAH5-Fy:b91fn5w) ([raw file](https://github.com/nitnelave/hopper/blob/2dbd4e7351e1ce89eb2b44a44f36f4e943d89c31/src/util/logging.h#L9)):*
> ```objc
> DECLARE_int32(verbosity);
> 
> enum Severity {
> ```

what about enum class ? I think we could go for it here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/41)*

**Comment by nitnelave** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/util/logging.cc, line 9 at r1](https://reviewable.io:443/reviews/nitnelave/hopper/41#-Kqh8gom64XmESyWuZZv:-KqhrHkTkDzBSCPFam-7:bph9lm7) ([raw file](https://github.com/nitnelave/hopper/blob/2dbd4e7351e1ce89eb2b44a44f36f4e943d89c31/src/util/logging.cc#L9)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

dead code or example?
</blockquote></details>

Example. Probably should make it clearer, though.

---

*[src/util/logging.h, line 9 at r1](https://reviewable.io:443/reviews/nitnelave/hopper/41#-Kqh8mILo9oXwRAH5-Fx:-KqhrN8A_JgJ5UBZFwW1:b7gr6mp) ([raw file](https://github.com/nitnelave/hopper/blob/2dbd4e7351e1ce89eb2b44a44f36f4e943d89c31/src/util/logging.h#L9)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

what about enum class ? I think we could go for it here
</blockquote></details>

No, I don't want to have to write `log(Severity::INFO) << "test";`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/41)*

**Comment by bloody76** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/41#-:-KqhwrUEtytKxVOfZLfm:bnfp4nl)*

**Comment by bloody76** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: 0 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/41#-:-Kqma1D40oJemVWkVSjE:bnfp4nl)*

**Comment by bloody76** [comment]
Reviewed 1 of 1 files at r4.
Review status: 1 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/41)*

**Comment by bloody76** [comment]
Reviewed 3 of 3 files at r5.
Review status: 1 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/41)*

**Comment by bloody76** [comment]
Reviewed 3 of 3 files at r6.
Review status: 2 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/41)*

**Comment by bloody76** [comment]
Reviewed 3 of 3 files at r7.
Review status: 5 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/41)*

**Comment by bloody76** [comment]
Reviewed 2 of 3 files at r8, 2 of 3 files at r9.
Review status: 8 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/41)*

**Comment by bloody76** [comment]
Reviewed 1 of 3 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/41)*

**Pull request merged**
