### PR TITLE
Use boost to get type names at compile time

### PR DESCRIPTION
**Pull request by bloody76**
This change is [Reviewable](https://reviewable.io/reviews/nitnelave/hopper/59)

### CODE REVIEW

**Comment by bloody76** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 41 at r1](https://reviewable.io:443/reviews/nitnelave/hopper/59#-Ks9YIK0xqpBF0X-4GQE:-Ks9YIK0xqpBF0X-4GQF:b-ntddjl) ([raw file](https://github.com/nitnelave/hopper/blob/f5787572eeb4a0d37b030626860d77bfa35462fd/CMakeLists.txt#L41)):*
> ```CMake
> 
> set(Boost_USE_MULTITHREADED ON)
> set(Boost_USE_STATIC_RUNTIME ON)
> ```

the multithreaded one may be useless, what do yo uthink ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/59)*

**Comment by nitnelave** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[.travis.yml, line 71 at r1](https://reviewable.io:443/reviews/nitnelave/hopper/59#-Ks9YaU6UaBw8jWbjoko:-Ks9YaU6UaBw8jWbjokp:b-ysu5x0) ([raw file](https://github.com/nitnelave/hopper/blob/f5787572eeb4a0d37b030626860d77bfa35462fd/.travis.yml#L71)):*
> ```YAML
> 
> 
> boost_install_includes: &boost_install_includes |
> ```

Move to cache, we don't want to download them every time. And maybe extract the subset that's needed, so that the cache is smaller?

---

*[CMakeLists.txt, line 33 at r1](https://reviewable.io:443/reviews/nitnelave/hopper/59#-Ks9Yu0VGcll-rDIJYw2:-Ks9Yu0VGcll-rDIJYw3:b631qax) ([raw file](https://github.com/nitnelave/hopper/blob/f5787572eeb4a0d37b030626860d77bfa35462fd/CMakeLists.txt#L33)):*
> ```CMake
>     -pedantic \
>     -Werror \
>     -fno-rtti \
> ```

Any reason? Does this fix the build? I'm afraid it might break exceptions, in which case it's another discussion

---

*[CMakeLists.txt, line 41 at r1](https://reviewable.io:443/reviews/nitnelave/hopper/59#-Ks9YIK0xqpBF0X-4GQE:-Ks9YjRMUJtE-wl2Og3z:b-734gc5) ([raw file](https://github.com/nitnelave/hopper/blob/f5787572eeb4a0d37b030626860d77bfa35462fd/CMakeLists.txt#L41)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

the multithreaded one may be useless, what do yo uthink ?
</blockquote></details>

If it works without, it's better to keep it simple.

---

*[src/util/variant.h, line 340 at r1](https://reviewable.io:443/reviews/nitnelave/hopper/59#-Ks9Z33CCC4CG44NE2XJ:-Ks9Z33CCC4CG44NE2XK:b-dhgs09) ([raw file](https://github.com/nitnelave/hopper/blob/f5787572eeb4a0d37b030626860d77bfa35462fd/src/util/variant.h#L340)):*
> ```objc
>     if (type_index_ == internals::DirectType<T, Types...>::index)
>       return get_unchecked<T>();  // NOLINT
>     throw BadVariantAccess(std::string("in get<") + boost::typeindex::type_id<T>().pretty_name() + ">()");
> ```

Factor into a private function?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/59)*

**Comment by bloody76** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[CMakeLists.txt, line 33 at r1](https://reviewable.io:443/reviews/nitnelave/hopper/59#-Ks9Yu0VGcll-rDIJYw2:-Ks9_ZQA_oQzeBkb6yPc:b-tlu8bg) ([raw file](https://github.com/nitnelave/hopper/blob/f5787572eeb4a0d37b030626860d77bfa35462fd/CMakeLists.txt#L33)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

Any reason? Does this fix the build? I'm afraid it might break exceptions, in which case it's another discussion
</blockquote></details>

Yes it does fix the build

---

*[CMakeLists.txt, line 41 at r1](https://reviewable.io:443/reviews/nitnelave/hopper/59#-Ks9YIK0xqpBF0X-4GQE:-Ks9_uGX5CSaYKVtJIx5:b-3x4rcy) ([raw file](https://github.com/nitnelave/hopper/blob/f5787572eeb4a0d37b030626860d77bfa35462fd/CMakeLists.txt#L41)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

If it works without, it's better to keep it simple.
</blockquote></details>

seems like both are not needed.

---

*[src/util/variant.h, line 340 at r1](https://reviewable.io:443/reviews/nitnelave/hopper/59#-Ks9Z33CCC4CG44NE2XJ:-Ks9bWnIpMFYNk4iGKFz:b-896fix) ([raw file](https://github.com/nitnelave/hopper/blob/f5787572eeb4a0d37b030626860d77bfa35462fd/src/util/variant.h#L340)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

Factor into a private function?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/59)*

**Comment by bloody76** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/59)*

**Comment by nitnelave** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[CMakeLists.txt, line 33 at r1](https://reviewable.io:443/reviews/nitnelave/hopper/59#-Ks9Yu0VGcll-rDIJYw2:-Ks9cx3jN7oPnb7EzpkY:b-oupcas) ([raw file](https://github.com/nitnelave/hopper/blob/f5787572eeb4a0d37b030626860d77bfa35462fd/CMakeLists.txt#L33)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

Yes it does fix the build
</blockquote></details>

Had a look, it seems exceptions don't need RTTI, so we should be okay with this option.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/59)*

**Comment by nitnelave** [comment]
:lgtm: once the resource is cached

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/59#-:-Ks9d4elVZo3OWvqxZZL:bz50ikl)*

**Comment by bloody76** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis.yml, line 71 at r1](https://reviewable.io:443/reviews/nitnelave/hopper/59#-Ks9YaU6UaBw8jWbjoko:-KsAKTl-EbU66xHmz7p7:b-896fix) ([raw file](https://github.com/nitnelave/hopper/blob/f5787572eeb4a0d37b030626860d77bfa35462fd/.travis.yml#L71)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

Move to cache, we don't want to download them every time. And maybe extract the subset that's needed, so that the cache is smaller?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/59)*

**Comment by bloody76** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/59)*

**Pull request merged**
