### PR TITLE
Support argument declaration for functions

### PR DESCRIPTION
**Pull request by bloody76**
This change is [Reviewable](https://reviewable.io/reviews/nitnelave/hopper/48)

### CODE REVIEW

**Comment by nitnelave** [comment]
Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/codegen/codegen_function.cc, line 47 at r1](https://reviewable.io:443/reviews/nitnelave/hopper/48#-KqrZeux7qljUH4ZSEQI:-KqrZeux7qljUH4ZSEQJ:b-x7vyfd) ([raw file](https://github.com/nitnelave/hopper/blob/eea90e62404afe83ff3a9470215e365c4b9cbea2/src/codegen/codegen_function.cc#L47)):*
> ```cpp
>   llvm_function->setCallingConv(CallingConv::C);
> 
>   // Name the parameters.
> ```

Add an assert that the two lists are the same size. And you don't need `std::` for begin and end, because of argument-dependent lookup.

---

*[test/resources/ir/function_with_arg.gh, line 1 at r1](https://reviewable.io:443/reviews/nitnelave/hopper/48#-Kqr_8l4kZHcd4aHqSYF:-Kqr_8l4kZHcd4aHqSYG:b51ed9) ([raw file](https://github.com/nitnelave/hopper/blob/eea90e62404afe83ff3a9470215e365c4b9cbea2/test/resources/ir/function_with_arg.gh#L1)):*
> ```
> fun main(a: Int) {
> ```

Int32, until we have type aliases

---

*[test/resources/ir/function_with_args.gh, line 1 at r1](https://reviewable.io:443/reviews/nitnelave/hopper/48#-Kqr_Izscx30MBf3MjnU:-Kqr_IztuxIhQfCihZSR:b-euzhjy) ([raw file](https://github.com/nitnelave/hopper/blob/eea90e62404afe83ff3a9470215e365c4b9cbea2/test/resources/ir/function_with_args.gh#L1)):*
> ```
> fun main(a: Int, b: Int) {
> ```

I'm not super fond of calling them `main`, since we'll eventually enforce a signature for main

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/48)*

**Comment by bloody76** [comment]
Review status: 6 of 20 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/resources/ir/function_with_args.gh, line 1 at r1](https://reviewable.io:443/reviews/nitnelave/hopper/48#-Kqr_Izscx30MBf3MjnU:-KqvhaznOJ4QoPuQkVQW:b-896fix) ([raw file](https://github.com/nitnelave/hopper/blob/eea90e62404afe83ff3a9470215e365c4b9cbea2/test/resources/ir/function_with_args.gh#L1)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

I'm not super fond of calling them `main`, since we'll eventually enforce a signature for main
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/48)*

**Comment by bloody76** [comment]
Review status: 6 of 20 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/resources/ir/function_with_arg.gh, line 1 at r1](https://reviewable.io:443/reviews/nitnelave/hopper/48#-Kqr_8l4kZHcd4aHqSYF:-KqvjZqSl0PD9S9fDBjE:b-896fix) ([raw file](https://github.com/nitnelave/hopper/blob/eea90e62404afe83ff3a9470215e365c4b9cbea2/test/resources/ir/function_with_arg.gh#L1)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

Int32, until we have type aliases
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/48)*

**Comment by bloody76** [comment]
Review status: 5 of 20 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/codegen/codegen_function.cc, line 47 at r1](https://reviewable.io:443/reviews/nitnelave/hopper/48#-KqrZeux7qljUH4ZSEQI:-KqvkHgS8nrocsrzN50g:b-896fix) ([raw file](https://github.com/nitnelave/hopper/blob/eea90e62404afe83ff3a9470215e365c4b9cbea2/src/codegen/codegen_function.cc#L47)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

Add an assert that the two lists are the same size. And you don't need `std::` for begin and end, because of argument-dependent lookup.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/48)*

**Comment by nitnelave** [comment]
Sorry, how did I miss that? The syntax has a `val` or `mut`:
`fun test(val a : Int32)`

---

Review status: 5 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/48#-:-KqxDspokT1tb4WvXqRE:b-6j5vhz)*

**Comment by bloody76** [comment]
Done !

---

Review status: 2 of 21 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/48#-:-KqxZ1iBL-Twpivk7NG1:bs7wuaw)*

**Comment by nitnelave** [comment]
Reviewed 2 of 20 files at r2.
Review status: 4 of 22 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/ast/function_argument_declaration.h, line 13 at r2](https://reviewable.io:443/reviews/nitnelave/hopper/48#-Kr0DFpCjDdjUGkSea8z:-Kr0DFpCjDdjUGkSea9-:b-qcvgct) ([raw file](https://github.com/nitnelave/hopper/blob/10bac0df2a8028ead9ea7cf69f2babbbb39c8dc7/src/ast/function_argument_declaration.h#L13)):*
> ```objc
>   FunctionArgumentDeclaration(lexer::Range location, Identifier id, Type type,
>                               bool mut)
>       : ASTNode(std::move(location)),
> ```

Why not have it be a variable declaration? or contain one? Or extract the common part into an abstract class? There's much overlap here (intentionally, I might add)

---

*[src/parser/parser.cc, line 223 at r2](https://reviewable.io:443/reviews/nitnelave/hopper/48#-Kr-wKmFpvkkRA6DWsBb:-Kr-wKmFpvkkRA6DWsBc:b-17opxq) ([raw file](https://github.com/nitnelave/hopper/blob/10bac0df2a8028ead9ea7cf69f2babbbb39c8dc7/src/parser/parser.cc#L223)):*
> ```cpp
> 
>   if (!value.is_ok() && !type.is_ok()) {
>     return ParseError("Expected either a type, either a value to infer from",
> ```

either/or, not either/either.
And no comma: "Expected either a type or a default value to infer from"

---

*[src/parser/parser.cc, line 303 at r2](https://reviewable.io:443/reviews/nitnelave/hopper/48#-Kr0DYi1UG-sYfl_0Atl:-Kr0DYi1UG-sYfl_0Atm:be9n9xv) ([raw file](https://github.com/nitnelave/hopper/blob/10bac0df2a8028ead9ea7cf69f2babbbb39c8dc7/src/parser/parser.cc#L303)):*
> ```cpp
>     arguments.push_back(std::make_unique<ast::FunctionArgumentDeclaration>(
>         location.range(), val_decl->id(),
>         std::move(val_decl->type().value_or_die()), val_decl->is_mutable()));
> ```

You don't know if there is a type, you can't use value_or_die()

---

*[tools/clang-format.sh, line 14 at r2](https://reviewable.io:443/reviews/nitnelave/hopper/48#-Kr0DpCNfFWkuEXxF-mF:-Kr0DpCNfFWkuEXxF-mG:bo5fv5f) ([raw file](https://github.com/nitnelave/hopper/blob/10bac0df2a8028ead9ea7cf69f2babbbb39c8dc7/tools/clang-format.sh#L14)):*
> ```Shell
> FORMAT_CMD="clang-format -style=Google"
> 
> FIND_CMD="find ${PROJECT_DIR}/src/ ${PROJECT_DIR}/test/ -regex '.*\.[hc]\{1,2\}' -type f"
> ```

Will have to rebase after PR #44  is merged

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/48)*

**Comment by bloody76** [comment]
Review status: 4 of 22 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/ast/function_argument_declaration.h, line 13 at r2](https://reviewable.io:443/reviews/nitnelave/hopper/48#-Kr0DFpCjDdjUGkSea8z:-KrApZyb9DB01MttMnsA:bfpyvfd) ([raw file](https://github.com/nitnelave/hopper/blob/10bac0df2a8028ead9ea7cf69f2babbbb39c8dc7/src/ast/function_argument_declaration.h#L13)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

Why not have it be a variable declaration? or contain one? Or extract the common part into an abstract class? There's much overlap here (intentionally, I might add)
</blockquote></details>

It would be much better indeed, I just have issues regarding the pretty printer, I will give it another try, maybe last time I was tired.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/48)*

**Comment by bloody76** [comment]
Review status: 0 of 32 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/parser/parser.cc, line 223 at r2](https://reviewable.io:443/reviews/nitnelave/hopper/48#-Kr-wKmFpvkkRA6DWsBb:-KrBBhFGY94udtanRgqt:b-896fix) ([raw file](https://github.com/nitnelave/hopper/blob/10bac0df2a8028ead9ea7cf69f2babbbb39c8dc7/src/parser/parser.cc#L223)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

either/or, not either/either.
And no comma: "Expected either a type or a default value to infer from"
</blockquote></details>

Done.

---

*[src/parser/parser.cc, line 303 at r2](https://reviewable.io:443/reviews/nitnelave/hopper/48#-Kr0DYi1UG-sYfl_0Atl:-KrBBjUxBPJAz1U_-eQR:b-896fix) ([raw file](https://github.com/nitnelave/hopper/blob/10bac0df2a8028ead9ea7cf69f2babbbb39c8dc7/src/parser/parser.cc#L303)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

You don't know if there is a type, you can't use value_or_die()
</blockquote></details>

Done.

---

*[tools/clang-format.sh, line 14 at r2](https://reviewable.io:443/reviews/nitnelave/hopper/48#-Kr0DpCNfFWkuEXxF-mF:-KrBBkxpaT4t7jtR8mZr:b2nhtan) ([raw file](https://github.com/nitnelave/hopper/blob/10bac0df2a8028ead9ea7cf69f2babbbb39c8dc7/tools/clang-format.sh#L14)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

Will have to rebase after PR #44  is merged
</blockquote></details>

Yup

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/48)*

**Comment by nitnelave** [comment]
Review status: 0 of 31 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/ast/function_argument_declaration.h, line 16 at r3](https://reviewable.io:443/reviews/nitnelave/hopper/48#-KrBLIEadCo0Hlqbipcf:-KrBLIEbk_gfjiYgbtWn:bgvqceh) ([raw file](https://github.com/nitnelave/hopper/blob/8baba116f9f55aaa4a33a5c7db585726df59f55e/src/ast/function_argument_declaration.h#L16)):*
> ```objc
>                               Option<std::unique_ptr<Value>> value, bool mut)
>       : VariableDeclaration(std::move(location), std::move(id), std::move(type),
>                             std::move(value), mut) {}
> ```

I would put an assert that we have at least either a type or a value.

---

*[src/parser/parser.cc, line 201 at r3](https://reviewable.io:443/reviews/nitnelave/hopper/48#-KrBLcNzKqUIkcef7-5W:-KrBLcNzKqUIkcef7-5X:br877yd) ([raw file](https://github.com/nitnelave/hopper/blob/8baba116f9f55aaa4a33a5c7db585726df59f55e/src/parser/parser.cc#L201)):*
> ```cpp
> template <class Declaration>
> Parser::ErrorOrPtr<Declaration> Parser::parse_variable_declaration() {
>   static_assert(std::is_base_of<ast::VariableDeclaration, Declaration>::value,
> ```

I like that :) 

---

*[tools/clang-format.sh, line 14 at r2](https://reviewable.io:443/reviews/nitnelave/hopper/48#-Kr0DpCNfFWkuEXxF-mF:-KrBLkZeYQARvVHGhvNH:b-3p1hu2) ([raw file](https://github.com/nitnelave/hopper/blob/10bac0df2a8028ead9ea7cf69f2babbbb39c8dc7/tools/clang-format.sh#L14)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

Yup
</blockquote></details>

Meanwhile, can you remove this change from the PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/48)*

**Comment by bloody76** [comment]
Review status: 0 of 31 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/ast/function_argument_declaration.h, line 16 at r3](https://reviewable.io:443/reviews/nitnelave/hopper/48#-KrBLIEadCo0Hlqbipcf:-KrBVuoDxgqArzyXQ9D4:b-td7c44) ([raw file](https://github.com/nitnelave/hopper/blob/8baba116f9f55aaa4a33a5c7db585726df59f55e/src/ast/function_argument_declaration.h#L16)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

I would put an assert that we have at least either a type or a value.
</blockquote></details>

Indeed, I put it at the parse_variable_declaration level but I will do it here also !

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/48)*

**Comment by bloody76** [comment]
Review status: 0 of 30 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/ast/function_argument_declaration.h, line 16 at r3](https://reviewable.io:443/reviews/nitnelave/hopper/48#-KrBLIEadCo0Hlqbipcf:-KrBYmnwc-eu-NbW2h8E:b-896fix) ([raw file](https://github.com/nitnelave/hopper/blob/8baba116f9f55aaa4a33a5c7db585726df59f55e/src/ast/function_argument_declaration.h#L16)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

Indeed, I put it at the parse_variable_declaration level but I will do it here also !
</blockquote></details>

Done.

---

*[tools/clang-format.sh, line 14 at r2](https://reviewable.io:443/reviews/nitnelave/hopper/48#-Kr0DpCNfFWkuEXxF-mF:-KrBYlTj0f5I9kJNDtBJ:b-896fix) ([raw file](https://github.com/nitnelave/hopper/blob/10bac0df2a8028ead9ea7cf69f2babbbb39c8dc7/tools/clang-format.sh#L14)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

Meanwhile, can you remove this change from the PR?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/48)*

**Comment by nitnelave** [comment]
Review status: 0 of 30 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ast/function_argument_declaration.h, line 16 at r3](https://reviewable.io:443/reviews/nitnelave/hopper/48#-KrBLIEadCo0Hlqbipcf:-KrBfw1w-PgOIinzZ4DB:b-y62rj4) ([raw file](https://github.com/nitnelave/hopper/blob/8baba116f9f55aaa4a33a5c7db585726df59f55e/src/ast/function_argument_declaration.h#L16)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Erm, I don't see it...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/48)*

**Comment by bloody76** [comment]
Review status: 0 of 30 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ast/function_argument_declaration.h, line 16 at r3](https://reviewable.io:443/reviews/nitnelave/hopper/48#-KrBLIEadCo0Hlqbipcf:-KrBogjS5ExTy5iySI9k:b-sw15cg) ([raw file](https://github.com/nitnelave/hopper/blob/8baba116f9f55aaa4a33a5c7db585726df59f55e/src/ast/function_argument_declaration.h#L16)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

Erm, I don't see it...
</blockquote></details>

its in variable_declaration.h, this way we assert for all the kind of variable declaration

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/48)*

**Comment by nitnelave** [comment]
:lgtm:

---

Review status: 0 of 30 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ast/function_argument_declaration.h, line 16 at r3](https://reviewable.io:443/reviews/nitnelave/hopper/48#-KrBLIEadCo0Hlqbipcf:-KrBryrMfBaBDTdMPzoL:bweo038) ([raw file](https://github.com/nitnelave/hopper/blob/8baba116f9f55aaa4a33a5c7db585726df59f55e/src/ast/function_argument_declaration.h#L16)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

its in variable_declaration.h, this way we assert for all the kind of variable declaration
</blockquote></details>

OK, Got it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/48#-:-KrBs4IxWZbWmmoXDVp4:bnfp4nl)*

**Pull request merged**
