### PR TITLE
Add pretty printer for if statements.

### PR DESCRIPTION
**Pull request by bloody76**
This change is [Reviewable](https://reviewable.io/reviews/nitnelave/hopper/53)

### CODE REVIEW

**Comment by nitnelave** [comment]
Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/parser/parser.cc, line 237 at r1](https://reviewable.io:443/reviews/nitnelave/hopper/53#-KrFNsHAl_1fvjZAPPBp:-KrFNsHBt7UaUJLpDcWG:b-lcolig) ([raw file](https://github.com/nitnelave/hopper/blob/13d0a00c209e898a51da8ded679a14ae2db6eb41/src/parser/parser.cc#L237)):*
> ```cpp
> }
> 
> Parser::ErrorOrPtr<ast::BlockStatement> Parser::parse_statement_as_list() {
> ```

parse_statement_or_list? The fact that it returns a list of statements is already included in the return type

---

*[src/parser/parser.h, line 122 at r1](https://reviewable.io:443/reviews/nitnelave/hopper/53#-KrFO0gKLD7Sh7xuvTca:-KrFO0gKLD7Sh7xuvTcb:bbemrat) ([raw file](https://github.com/nitnelave/hopper/blob/13d0a00c209e898a51da8ded679a14ae2db6eb41/src/parser/parser.h#L122)):*
> ```objc
>       IdentifierType type = IdentifierType::QUALIFIED);
> 
>   ErrorOrPtr<ast::BlockStatement> parse_statement_as_list();
> ```

Documentation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/53)*

**Comment by bloody76** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/parser/parser.cc, line 237 at r1](https://reviewable.io:443/reviews/nitnelave/hopper/53#-KrFNsHAl_1fvjZAPPBp:-KrFPtDyw550MAvTISMs:b5483u6) ([raw file](https://github.com/nitnelave/hopper/blob/13d0a00c209e898a51da8ded679a14ae2db6eb41/src/parser/parser.cc#L237)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

parse_statement_or_list? The fact that it returns a list of statements is already included in the return type
</blockquote></details>

or_list is misleading I think, because it's either a list or a statement that we transform as a list, you think the or_list is better ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/53)*

**Comment by nitnelave** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/parser/parser.cc, line 237 at r1](https://reviewable.io:443/reviews/nitnelave/hopper/53#-KrFNsHAl_1fvjZAPPBp:-KrFY80cXZSP_e1NeO6c:b-kymn63) ([raw file](https://github.com/nitnelave/hopper/blob/13d0a00c209e898a51da8ded679a14ae2db6eb41/src/parser/parser.cc#L237)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

or_list is misleading I think, because it's either a list or a statement that we transform as a list, you think the or_list is better ?
</blockquote></details>

What you are doing: parsing either a statement or a block (a list).
What you return: a block.

For me, it makes perfect sense to call that parse_statement_or_list (or parse_statement_or_block)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/53)*

**Comment by bloody76** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/parser/parser.cc, line 237 at r1](https://reviewable.io:443/reviews/nitnelave/hopper/53#-KrFNsHAl_1fvjZAPPBp:-KrGYiTz0iyltryicheO:b-s6s7y5) ([raw file](https://github.com/nitnelave/hopper/blob/13d0a00c209e898a51da8ded679a14ae2db6eb41/src/parser/parser.cc#L237)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

What you are doing: parsing either a statement or a block (a list).
What you return: a block.

For me, it makes perfect sense to call that parse_statement_or_list (or parse_statement_or_block)
</blockquote></details>

Ok yeah why not, it's just that it seems misleading as it returns a list and it should return a statement from the name, but let's go with that

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/53)*

**Comment by bloody76** [comment]
Review status: 19 of 21 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/parser/parser.h, line 122 at r1](https://reviewable.io:443/reviews/nitnelave/hopper/53#-KrFO0gKLD7Sh7xuvTca:-KrUn9P7QhSKeab3iD2R:b-896fix) ([raw file](https://github.com/nitnelave/hopper/blob/13d0a00c209e898a51da8ded679a14ae2db6eb41/src/parser/parser.h#L122)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

Documentation
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/53)*

**Comment by bloody76** [comment]
Review status: 19 of 21 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/parser/parser.cc, line 237 at r1](https://reviewable.io:443/reviews/nitnelave/hopper/53#-KrFNsHAl_1fvjZAPPBp:-KrUnAujzRxXYQsleP-q:b-896fix) ([raw file](https://github.com/nitnelave/hopper/blob/13d0a00c209e898a51da8ded679a14ae2db6eb41/src/parser/parser.cc#L237)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

Ok yeah why not, it's just that it seems misleading as it returns a list and it should return a statement from the name, but let's go with that
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/53)*

**Comment by bloody76** [comment]
Reviewed 1 of 2 files at r2.
Review status: 20 of 21 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/53)*

**Comment by bloody76** [comment]
Reviewed 1 of 21 files at r1.
Review status: 20 of 21 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/53)*

**Comment by bloody76** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/53)*

**Comment by nitnelave** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/53#-:-KrUw1hgMh2-8W2EXYJi:bnfp4nl)*

**Comment by nitnelave** [comment]
But do fix the build with travis

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/53#-:-KrUw8H9jazOn8fNYb-C:b2phdqy)*

**Comment by bloody76** [comment]
Reviewed 2 of 21 files at r1.
Review status: 19 of 21 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/53)*

**Comment by bloody76** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/53)*

**Pull request merged**
