### PR TITLE
Simplify the IfStatement node

### PR DESCRIPTION
**Pull request by nitnelave**
By having a simple structure, the code generation, printing, and general handling is simplified.

---
This change is [Reviewable](https://reviewable.io/reviews/nitnelave/hopper/57)

### CODE REVIEW

**Comment by bloody76** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 20 of 20 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/codegen/codegen_statement.cc, line 76 at r5](https://reviewable.io:443/reviews/nitnelave/hopper/57#-Ks7wqTTSQs1m_sB3Srb:-Ks7wqTTSQs1m_sB3Src:b-i6920s) ([raw file](https://github.com/nitnelave/hopper/blob/e9325cc3eb138f12dda832b76c627650176d333a/src/codegen/codegen_statement.cc#L76)):*
>  log(ERROR)

Why ERROR ? Why not TRACE or DEBUG ?

---

*[src/codegen/codegen_statement.cc, line 97 at r5](https://reviewable.io:443/reviews/nitnelave/hopper/57#-Ks7x08kaagq031OSz_D:-Ks7x08kaagq031OSz_E:bhn1h5q) ([raw file](https://github.com/nitnelave/hopper/blob/e9325cc3eb138f12dda832b76c627650176d333a/src/codegen/codegen_statement.cc#L97)):*
> ```cpp
>   ir_builder_.SetInsertPoint(if_start_block);
>   ir_builder_.CreateCondBr(equality, if_block,
>                            else_block.is_ok() ? else_block.value_or_die()
> ```

else_block.value_or(ifend_block.value_or_die()) ?

---

*[test/resources/ir/if_elseif_statement.gh, line 5 at r5](https://reviewable.io:443/reviews/nitnelave/hopper/57#-Ks7xlFCMcMlPdOMVkTJ:-Ks7xlFCMcMlPdOMVkTK:bfx2opg) ([raw file](https://github.com/nitnelave/hopper/blob/e9325cc3eb138f12dda832b76c627650176d333a/test/resources/ir/if_elseif_statement.gh#L5)):*
> ```
>     1;
>   } else {
>   if (2) {
> ```

why changing the test ? Identation anyway

---

*[test/resources/ir/if_statement2.gh, line 5 at r5](https://reviewable.io:443/reviews/nitnelave/hopper/57#-Ks7xzGuzsQ_KE4PAcKS:-Ks7xzGvAUg6BjfURl8Q:b-rp1ae4) ([raw file](https://github.com/nitnelave/hopper/blob/e9325cc3eb138f12dda832b76c627650176d333a/test/resources/ir/if_statement2.gh#L5)):*
> ```
>     1;
>   }
> ```

same, why changing the test ? 

---

*[test/resources/ir/if_statement3.ref, line 0 at r5](https://reviewable.io:443/reviews/nitnelave/hopper/57#-Ks7y56MpZjClQ4NyeKf:-Ks7y56MpZjClQ4NyeKg:blgd6ck) ([raw file](https://github.com/nitnelave/hopper/blob/e9325cc3eb138f12dda832b76c627650176d333a/test/resources/ir/if_statement3.ref#L0)):*
why deleting ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/57)*

**Comment by nitnelave** [comment]
Review status: 21 of 23 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/codegen/codegen_statement.cc, line 76 at r5](https://reviewable.io:443/reviews/nitnelave/hopper/57#-Ks7wqTTSQs1m_sB3Srb:-Ks8-bKH4NBssPM_hHgT:b-1g9ngq) ([raw file](https://github.com/nitnelave/hopper/blob/e9325cc3eb138f12dda832b76c627650176d333a/src/codegen/codegen_statement.cc#L76)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

>  log(ERROR)

Why ERROR ? Why not TRACE or DEBUG ?
</blockquote></details>

Debugging leftovers, I wanted it to display during test execution. Removed.

---

*[src/codegen/codegen_statement.cc, line 97 at r5](https://reviewable.io:443/reviews/nitnelave/hopper/57#-Ks7x08kaagq031OSz_D:-Ks8-gXX9KwkveGHixfw:b-ylod5e) ([raw file](https://github.com/nitnelave/hopper/blob/e9325cc3eb138f12dda832b76c627650176d333a/src/codegen/codegen_statement.cc#L97)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

else_block.value_or(ifend_block.value_or_die()) ?
</blockquote></details>

no, because the argument of the function is greedily evaluated, leading to the `or_die()` part.

---

*[test/resources/ir/if_statement2.gh, line 5 at r5](https://reviewable.io:443/reviews/nitnelave/hopper/57#-Ks7xzGuzsQ_KE4PAcKS:-Ks8-zwmpseOg0mwaWQZ:b4v3dae) ([raw file](https://github.com/nitnelave/hopper/blob/e9325cc3eb138f12dda832b76c627650176d333a/test/resources/ir/if_statement2.gh#L5)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

same, why changing the test ? 
</blockquote></details>

Here, the test is the if_statement3 that I just moved to if_statement2 after deleting this one. I deleted it because it was the same test as if_statement1, except that the if did not have braces. This is a syntax difference, not a semantic one, so it should be checked at the pretty-printer level.

---

*[test/resources/ir/if_statement3.ref, line  at r5](https://reviewable.io:443/reviews/nitnelave/hopper/57#-Ks7y56MpZjClQ4NyeKf:-Ks80KDf3xSoHPTI6XHh:b-q64pkt) ([raw file](https://github.com/nitnelave/hopper/blob/e9325cc3eb138f12dda832b76c627650176d333a/test/resources/ir/if_statement3.ref#L)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

why deleting ?
</blockquote></details>

See above.

---

*[test/resources/ir/if_elseif_statement.gh, line 5 at r5](https://reviewable.io:443/reviews/nitnelave/hopper/57#-Ks7xlFCMcMlPdOMVkTJ:-Ks8-txW1BcTv9k3atan:bjgohjq) ([raw file](https://github.com/nitnelave/hopper/blob/e9325cc3eb138f12dda832b76c627650176d333a/test/resources/ir/if_elseif_statement.gh#L5)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

why changing the test ? Identation anyway
</blockquote></details>

debugging leftovers, reverted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/57)*

**Comment by bloody76** [comment]
Reviewed 1 of 3 files at r6.
Review status: 22 of 23 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/57)*

**Comment by bloody76** [comment]
:lgtm:

---

Review status: 22 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/57#-:-Ks8BR_Jb-Yvh78b3ZQk:bnfp4nl)*

**Pull request merged**
