### PR TITLE
Fix bug in pretty printing to print function declaration block

### PR DESCRIPTION
**Pull request by bloody76**
This change is [Reviewable](https://reviewable.io/reviews/nitnelave/hopper/50)

### CODE REVIEW

**Comment by nitnelave** [comment]
Can you add empty block/function test?

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/50#-:-KqxDIsmGpgkRuqbzex6:b-hj0qup)*

**Comment by nitnelave** [comment]
:lgtm: apart from my comment above

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/50#-:-KqxDSJnswvVhGK1RgOR:begl2o3)*

**Comment by nitnelave** [comment]
Reviewed 4 of 4 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/50)*

**Comment by bloody76** [comment]
Done !

---

Review status: 4 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/50#-:-KqxGPrGoLKURoOV5aaR:bs7wuaw)*

**Pull request merged**
