### PR TITLE
add contribution guidelines

### PR DESCRIPTION
**Pull request by nitnelave**
This change is [Reviewable](https://reviewable.io/reviews/nitnelave/hopper/43)

### CODE REVIEW

**Comment by bloody76** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[CONTRIBUTING.md, line 32 at r1](https://reviewable.io:443/reviews/nitnelave/hopper/43#-Kqh6B9d9sceaBOmOIs-:-Kqh6B9d9sceaBOmOIs0:b-ersgpb) ([raw file](https://github.com/nitnelave/hopper/blob/ef003f82a6cf081d69223bf9f8f6831e578f684c/CONTRIBUTING.md#L32)):*
> ```Markdown
> guide](https://google.github.io/styleguide/cppguide.html), but with slightly
> different naming conventions. All types (except standard ones) are in
> _CamelCase_, all functions and variables in _snake\_case_.
> ```

this is camelCase, this is PascalCase

---

*[CONTRIBUTING.md, line 48 at r1](https://reviewable.io:443/reviews/nitnelave/hopper/43#-Kqh6SCvblvJV_aCnLjj:-Kqh6SCvblvJV_aCnLjk:b-1k2q7u) ([raw file](https://github.com/nitnelave/hopper/blob/ef003f82a6cf081d69223bf9f8f6831e578f684c/CONTRIBUTING.md#L48)):*
> ```Markdown
> - Make sure `make check` still passes.
> - Create logically separated commits (more on that later).
> - Write tests for your feature.
> ```

Normally it would be better to write tests for your feature first, then check that it indeed fails, then write code until it works

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/43)*

**Comment by bloody76** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/43)*

**Comment by nitnelave** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[CONTRIBUTING.md, line 48 at r1](https://reviewable.io:443/reviews/nitnelave/hopper/43#-Kqh6SCvblvJV_aCnLjj:-KqhqWdu-7DLS6ES3GYJ:b-h77v7) ([raw file](https://github.com/nitnelave/hopper/blob/ef003f82a6cf081d69223bf9f8f6831e578f684c/CONTRIBUTING.md#L48)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

Normally it would be better to write tests for your feature first, then check that it indeed fails, then write code until it works
</blockquote></details>

True, but they shouldn't be committed before the feature. Anyway, experienced coders know how to code, they don't need me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/43)*

**Comment by nitnelave** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[CONTRIBUTING.md, line 32 at r1](https://reviewable.io:443/reviews/nitnelave/hopper/43#-Kqh6B9d9sceaBOmOIs-:-KqjBIZwte87LW13oao0:b-896fix) ([raw file](https://github.com/nitnelave/hopper/blob/ef003f82a6cf081d69223bf9f8f6831e578f684c/CONTRIBUTING.md#L32)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

this is camelCase, this is PascalCase
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/43)*

**Comment by bloody76** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/43#-:-KqlE0iTkRDY9zFGB4yh:bnfp4nl)*

**Comment by bloody76** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/43#-:-KqnL5enOQoyp9s3Ez_t:bnfp4nl)*

**Pull request merged**
