### PR TITLE
Fix compilation on mac: need to include libgen.h

### PR DESCRIPTION
**Pull request by bloody76**
Compilation broken on mac, needs to include libgen.h to use the basename symbol in main

---
This change is [Reviewable](https://reviewable.io/reviews/nitnelave/hopper/52)

### CODE REVIEW

**Comment by nitnelave** [comment]
What is libgen.h?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/52#-:-KrBgKwzbOKh9UwXnfnm:b-h6pb8l)*

**Comment by bloody76** [comment]
It declares a few externals, including the one we are interested for, basename. http://pubs.opengroup.org/onlinepubs/7908799/xsh/libgen.h.html

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/52#-:-KrC-yGgv4zGLJLT0Ulw:b-7laccs)*

**Comment by nitnelave** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/52#-:-KrFY-l8H1uyHqR9LrMP:bnfp4nl)*

**Comment by nitnelave** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/52)*

**Pull request merged**
