### PR TITLE
Added support for if, else if, else to the parser + pretty printer

### PR DESCRIPTION
**Pull request by bloody76**
This change is [Reviewable](https://reviewable.io/reviews/nitnelave/hopper/51)

### CODE REVIEW

**Comment by nitnelave** [comment]
So you also plan to have if as a value?

I want to be able to write `val a = if (cond) 3 else 4;`

---

Reviewed 1 of 20 files at r1.
Review status: 1 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/51#-:-Kr-vPs7DgU6lP7bk8uK:bkfl9di)*

**Comment by bloody76** [comment]
I thought it would be better to have it for later. As statement are not values, I think it would be nice to do it in another review maybe. I don't know if we should use the same `IfStatement` class as well, maybe we should go for another class like `IfValue`, what do you think ?

---

Review status: 1 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/51#-:-KrApprWS2UvoV3y5Atg:bt650xs)*

**Comment by nitnelave** [comment]
That works for me. The IfValue will probably be desugared into an IfStatement, though.

---

Review status: 1 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/51#-:-KrAzZSixYwEik8BLHUU:b-t7r050)*

**Comment by bloody76** [comment]
lgtm ?

---

Review status: 1 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/51#-:-KrBHC-mup5-M2Zp5baT:b-nzoors)*

**Comment by nitnelave** [comment]
:lgtm:

---

Review status: 1 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/51#-:-KrBJuHMx7Tq0X6SvIcH:bnfp4nl)*

**Pull request merged**
