### PR TITLE
Add return to void functions

### PR DESCRIPTION
**Pull request by nitnelave**
This PR adds a return statement at the end of functions returning Void, making the implicit return explicit.

---
This change is [Reviewable](https://reviewable.io/reviews/nitnelave/hopper/58)

### CODE REVIEW

**Comment by bloody76** [comment]
Reviewed 1 of 1 files at r1, 20 of 20 files at r2, 2 of 6 files at r3, 10 of 10 files at r4.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[src/transform/add_return.cc, line 14 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAUTM6IoUVSVbFRBZi:-KsAUTM6IoUVSVbFRBZj:b3neone) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.cc#L14)):*
> ```cpp
> void VoidFunctionReturnAdder::visit(ast::IfStatement* node) {
>   if (node->else_statement().is_ok()) {
>     ASTVisitor::visit(node->body().get());
> ```

why not node->body()->accept(*this); ?

---

*[src/transform/add_return.cc, line 16 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAUZCsvyZ-kjoW9QFF:-KsAUZCsvyZ-kjoW9QFG:bl3qbx7) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.cc#L16)):*
> ```cpp
>     ASTVisitor::visit(node->body().get());
>     bool if_returned = has_returned_;
>     has_returned_ = false;
> ```

no need for this as we are going down the children

---

*[src/transform/add_return.cc, line 17 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAUsoXPEAcQhC7eNWn:-KsAUsoXPEAcQhC7eNWo:b-ci6iq8) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.cc#L17)):*
> ```cpp
>     bool if_returned = has_returned_;
>     has_returned_ = false;
>     ASTVisitor::visit(node->else_statement().value_or_die().get());
> ```

same why not `->accept(*this); ` ?

---

*[src/transform/add_return.cc, line 32 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAUmLWuDAI9Kh3bh-e:-KsAUmLWuDAI9Kh3bh-f:b-tc3t65) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.cc#L32)):*
> ```cpp
>     const auto& statement = *stmt_it;
>     if (has_returned_) {
>       error_list_.add_error(statement->location(), "Unreachable code");
> ```

should be add_warning I think, valid code, maybe not the user intention though

---

*[src/transform/add_return.cc, line 42 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAUwtS85PmlGaw_FVQ:-KsAUwtS85PmlGaw_FVR:b16u2y8) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.cc#L42)):*
> ```cpp
> void VoidFunctionReturnAdder::visit(ast::FunctionDeclaration* node) {
>   has_returned_ = false;
>   ASTVisitor::visit(node);
> ```

I don't get it, why visiting the same node ?

---

*[src/transform/add_return.cc, line 44 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAVDC2MT8s_tjtgF16:-KsAVDC2MT8s_tjtgF17:bw2b5a9) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.cc#L44)):*
> ```cpp
>   ASTVisitor::visit(node);
> 
>   using StatementsBody = ast::FunctionDeclaration::StatementsBody;
> ```

put it closer to where its used in the first place

---

*[src/transform/add_return.cc, line 54 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAVuzgg7vB1F3hFmwB:-KsAVuzhiXiE4c1LEueX:b-7d4nyr) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.cc#L54)):*
> ```cpp
> 
>   if (has_returned_) {
>     CHECK(!statements->statements().empty()) << "Empty function that returned: " << node->name();
> ```

shouldn't be possible I think, is it an assert to make sure there isn't some wrong behavior ?

---

*[src/transform/add_return.h, line 22 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAWEWAlzMLFvO9j46t:-KsAWEWAlzMLFvO9j46u:bt1k4q8) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.h#L22)):*
> ```objc
>  private:
>   bool has_returned_ = false;
>   ast::ErrorList<> error_list_;
> ```

I wonder if we couldn't make this part of the ASTVisitor directly ... instead of defining it again and again

---

*[src/visitor/error_visitor.h, line 12 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAWOc7TY3SyFyDISso:-KsAWOc7TY3SyFyDISsp:b-g28pp8) ([raw file](https://github.com/nitnelave/hopper/blob/3969955fb3b6b9b182bac7c917a90cf669fddc83/src/visitor/error_visitor.h#L12)):*
> ```objc
> class VisitorError : public GenericError {
>  public:
>   VisitorError(const lexer::Range& range, const std::string& message)
> ```

where di you need to put it non const ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/58)*

**Comment by nitnelave** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[src/transform/add_return.cc, line 14 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAUTM6IoUVSVbFRBZi:-KsD80YBsB8gLx_RJasZ:brco5bb) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.cc#L14)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

why not node->body()->accept(*this); ?
</blockquote></details>

This would imply another virtual call, whereas here we already know the type of the node, so we can call directly `visit`.

---

*[src/transform/add_return.cc, line 16 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAUZCsvyZ-kjoW9QFF:-KsD8D5RPbYenegp7jrO:b-y9ycy8) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.cc#L16)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

no need for this as we are going down the children
</blockquote></details>

That would imply that we guarantee that children set it to false when they don't return, which is not true.

---

*[src/transform/add_return.cc, line 17 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAUsoXPEAcQhC7eNWn:-KsD8VwGLE9PkXY3z_4Y:b1s4sp8) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.cc#L17)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

same why not `->accept(*this); ` ?
</blockquote></details>

Same answer, we know the type (otherwise it wouldn't compile).

---

*[src/transform/add_return.cc, line 32 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAUmLWuDAI9Kh3bh-e:-KsD8_yJ6Px6JAJL2Tey:b-hwkpge) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.cc#L32)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

should be add_warning I think, valid code, maybe not the user intention though
</blockquote></details>

I kinda want it to be an error, since we remove the statements after. I think being a little harsh on the user is not too bad.

---

*[src/transform/add_return.cc, line 42 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAUwtS85PmlGaw_FVQ:-KsD8mTayM0RW0Bwg55-:b-uao5w2) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.cc#L42)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

I don't get it, why visiting the same node ?
</blockquote></details>

calling the parent function that will recurse into the children, rather than writing the recursion ourselves everywhere.

---

*[src/transform/add_return.cc, line 54 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAVuzgg7vB1F3hFmwB:-KsD8uXC-NxywE7udLbn:bx6ydbw) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.cc#L54)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

shouldn't be possible I think, is it an assert to make sure there isn't some wrong behavior ?
</blockquote></details>

yeah, a `CHECK` is a nice-looking assert, removed in release mode.

---

*[src/transform/add_return.h, line 22 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAWEWAlzMLFvO9j46t:-KsD91FVhXJ1C74cQGIr:b-h4nfy) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.h#L22)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

I wonder if we couldn't make this part of the ASTVisitor directly ... instead of defining it again and again
</blockquote></details>

Yeah, could be nice. Or another base class inheriting from ASTVisitor, maybe?

---

*[src/visitor/error_visitor.h, line 12 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAWOc7TY3SyFyDISso:-KsD9BgmIep3ZFC-G5he:b1r77jd) ([raw file](https://github.com/nitnelave/hopper/blob/3969955fb3b6b9b182bac7c917a90cf669fddc83/src/visitor/error_visitor.h#L12)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

where di you need to put it non const ?
</blockquote></details>

it's not about const vs non-const, it's about reference vs value. When we remove the statements, if we have an error pointing to their location, the reference is invalid, we need to copy it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/58)*

**Comment by bloody76** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/transform/add_return.cc, line 14 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAUTM6IoUVSVbFRBZi:-KsDAQ6OtktmfNPLwt1N:bg9txwf) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.cc#L14)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

This would imply another virtual call, whereas here we already know the type of the node, so we can call directly `visit`.
</blockquote></details>

I think its better to do a virtual call instead of calling unique_ptr::get

---

*[src/transform/add_return.cc, line 16 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAUZCsvyZ-kjoW9QFF:-KsDAeTpBtHcw_CSVz4G:b-l7yysg) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.cc#L16)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

That would imply that we guarantee that children set it to false when they don't return, which is not true.
</blockquote></details>

han yes indeed.

---

*[src/transform/add_return.cc, line 32 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAUmLWuDAI9Kh3bh-e:-KsDBHt21H61W-hmMP_d:bye14xq) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.cc#L32)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

I kinda want it to be an error, since we remove the statements after. I think being a little harsh on the user is not too bad.
</blockquote></details>

I am not a big fan honestly, putting it a warning and make the warnings errors by default would be better in my opinion. But we shouldn't force the user with habits

---

*[src/transform/add_return.cc, line 42 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAUwtS85PmlGaw_FVQ:-KsDB5VLq7twS-YXLdl1:b-ynf0iw) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.cc#L42)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

calling the parent function that will recurse into the children, rather than writing the recursion ourselves everywhere.
</blockquote></details>

but we only care about the body of the function right ? Why would you check for returns in non-statement things ?

---

*[src/transform/add_return.h, line 22 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAWEWAlzMLFvO9j46t:-KsDBlGN9ghh1EDVs2B-:b-7als0c) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.h#L22)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

Yeah, could be nice. Or another base class inheriting from ASTVisitor, maybe?
</blockquote></details>

what would be the point of another base class ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/58)*

**Comment by nitnelave** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/transform/add_return.cc, line 14 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAUTM6IoUVSVbFRBZi:-KsDD1RxDkvEkchdj5Jt:b-88chho) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.cc#L14)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

I think its better to do a virtual call instead of calling unique_ptr::get
</blockquote></details>

Why? There's nothing dangerous about `unique_ptr::get`.

---

*[src/transform/add_return.cc, line 32 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAUmLWuDAI9Kh3bh-e:-KsDDA13AZc9LuQr-5Qa:bm971fm) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.cc#L32)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

I am not a big fan honestly, putting it a warning and make the warnings errors by default would be better in my opinion. But we shouldn't force the user with habits
</blockquote></details>

If you have a look at Go, if you declare a variable and don't use it, it's a compile error. If you call a function and don't use the return value, it's a compile error. And from some time working at HeartFlow, I suspect that some companies have *thousands* of warnings in their codebase, and they wouldn't see one more or one less. I'm more in favor of errors when it doesn't make sense and is easily fixed.

---

*[src/transform/add_return.cc, line 42 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAUwtS85PmlGaw_FVQ:-KsDDgSBHUTPU_zrlyuZ:bqdxfmx) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.cc#L42)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

but we only care about the body of the function right ? Why would you check for returns in non-statement things ?
</blockquote></details>

Fair enough. Will change.

---

*[src/transform/add_return.h, line 22 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAWEWAlzMLFvO9j46t:-KsDDqHj58yLfP5-M1E4:b-8pmdnp) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.h#L22)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

what would be the point of another base class ?
</blockquote></details>

to add the `error_list`, because not all visitors produce errors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/58)*

**Comment by nitnelave** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/transform/add_return.cc, line 42 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAUwtS85PmlGaw_FVQ:-KsEOcxMLOHVnlj27FBL:b-896fix) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.cc#L42)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

Fair enough. Will change.
</blockquote></details>

Done.

---

*[src/transform/add_return.cc, line 44 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAVDC2MT8s_tjtgF16:-KsEOe2A3HePMOCYPDA7:b-896fix) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.cc#L44)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

put it closer to where its used in the first place
</blockquote></details>

Done.

---

*[src/transform/add_return.h, line 22 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAWEWAlzMLFvO9j46t:-KsERGwyXdNfuol_JXFS:b-896fix) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.h#L22)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

to add the `error_list`, because not all visitors produce errors.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/58)*

**Comment by bloody76** [comment]
Review status: 26 of 37 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/transform/add_return.cc, line 14 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAUTM6IoUVSVbFRBZi:-KsE80le1fcNoow3veBn:b-58477u) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.cc#L14)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

Why? There's nothing dangerous about `unique_ptr::get`.
</blockquote></details>

well its dangerous because you can copy this ptr then and you bypass the smart ptr concept

---

*[src/transform/add_return.cc, line 32 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAUmLWuDAI9Kh3bh-e:-KsE8TfHEYflxFdJjGIj:bz9w0cy) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.cc#L32)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

If you have a look at Go, if you declare a variable and don't use it, it's a compile error. If you call a function and don't use the return value, it's a compile error. And from some time working at HeartFlow, I suspect that some companies have *thousands* of warnings in their codebase, and they wouldn't see one more or one less. I'm more in favor of errors when it doesn't make sense and is easily fixed.
</blockquote></details>

I get the point, it's just that we should be able to ignore those errors at least

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/58)*

**Comment by bloody76** [comment]
Reviewed 2 of 4 files at r5, 2 of 9 files at r6.
Review status: 30 of 37 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/transform/add_return.cc, line 18 at r6](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsEcdpsWR8aJcpHWnJt:-KsEcdpsWR8aJcpHWnJu:b-fg1hsx) ([raw file](https://github.com/nitnelave/hopper/blob/e96ec31e9cb60890428a5781c55c4f4368970332/src/transform/add_return.cc#L18)):*
> ```cpp
>     has_returned_ = false;
>     visit(node->else_statement().value_or_die().get());
>     has_returned_ = has_returned_ && if_returned;
> ```

&&= but not really important ..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/58)*

**Comment by bloody76** [comment]
Reviewed 1 of 9 files at r6.
Review status: 31 of 37 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/58)*

**Comment by bloody76** [comment]
Reviewed 7 of 9 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/58)*

**Comment by nitnelave** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/transform/add_return.cc, line 14 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAUTM6IoUVSVbFRBZi:-KsEdZrfB0ugXldUpE9O:b-ueene0) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.cc#L14)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

well its dangerous because you can copy this ptr then and you bypass the smart ptr concept
</blockquote></details>

Copying the pointer itself is not dangerous, it's an observer pointer. What's dangerous is:
  - deleting the pointer. There is no `delete` in the whole project, and I intend to keep it that way
  - accessing it after it was destroyed. This is always possible (except in Rust), but in this context it's not.

Consider it the same as passing a reference.

---

*[src/transform/add_return.cc, line 32 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAUmLWuDAI9Kh3bh-e:-KsEe_ZSGZZR1xHDvGVZ:b-f6vgzt) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.cc#L32)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

I get the point, it's just that we should be able to ignore those errors at least
</blockquote></details>

For now, let's keep it at error. The language is a bit opinionated, on purpose. And in the future, we can always downgrade it to a warning (whereas going the other way is a breaking change).

---

*[src/transform/add_return.cc, line 18 at r6](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsEcdpsWR8aJcpHWnJt:-KsEe5WsM2JNxcZSdafb:b47gpka) ([raw file](https://github.com/nitnelave/hopper/blob/e96ec31e9cb60890428a5781c55c4f4368970332/src/transform/add_return.cc#L18)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

&&= but not really important ..
</blockquote></details>

That's not an operator. `&&=` doesn't exist. Anyway, in the last version, you'll see that I changed it to `= .. && ...;` because clang-tidy was complaining about an implicit cast to `int` with the `&=` expression.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/58)*

**Comment by bloody76** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/transform/add_return.cc, line 14 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAUTM6IoUVSVbFRBZi:-KsEgkW8GCmnLXgTI9J2:b-8ji8ki) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.cc#L14)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

Copying the pointer itself is not dangerous, it's an observer pointer. What's dangerous is:
  - deleting the pointer. There is no `delete` in the whole project, and I intend to keep it that way
  - accessing it after it was destroyed. This is always possible (except in Rust), but in this context it's not.

Consider it the same as passing a reference.
</blockquote></details>

I understand that it's safe in the current context, but still a bad design to me. Provided the get method is bad IMO in the unique_ptr interface anyway ...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/58)*

**Comment by bloody76** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/transform/add_return.cc, line 32 at r4](https://reviewable.io:443/reviews/nitnelave/hopper/58#-KsAUmLWuDAI9Kh3bh-e:-KsEh8tTn2LGnXHdReF9:b-j0gtz1) ([raw file](https://github.com/nitnelave/hopper/blob/0c5310559a375eaa174a79937727684c9ddb8455/src/transform/add_return.cc#L32)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

For now, let's keep it at error. The language is a bit opinionated, on purpose. And in the future, we can always downgrade it to a warning (whereas going the other way is a breaking change).
</blockquote></details>

Ok let's do this then !

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/58)*

**Comment by bloody76** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/58#-:-KsEhDetTn9JWpVGXHBe:bnfp4nl)*

**Pull request merged**
