### PR TITLE
Make regex work on Mac OS as well by not using the pipe operator

### PR DESCRIPTION
**Pull request by bloody76**
This change is [Reviewable](https://reviewable.io/reviews/nitnelave/hopper/44)

### CODE REVIEW

**Comment by nitnelave** [comment]
Did you test on linux as well?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/44#-:-KqrYNpQcq6tVZ_kBxqm:bhrn62x)*

**Comment by bloody76** [comment]
Didn't have the chance no. But it has higher probability to work on linux as it supports more features. Need to test though.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/44#-:-KqvkM8Hr9T748Ujd4jN:bzcoxgx)*

**Comment by nitnelave** [comment]
:lgtm: after a quick check on linux

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/44#-:-KqvtGnUw4UY7ypzRnEd:bl5xh68)*

**Comment by bloody76** [comment]
Was a good idea to check, turns out its not working on linux

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/44#-:-KrAoXFB2VYYpYRE1Db1:bv22uqj)*

**Comment by bloody76** [comment]
New version is working on linux and mac

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/44#-:-KrAoyJpcpnS8UFzCWK5:bb5xk0h)*

**Comment by nitnelave** [comment]
Good to go!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/44#-:-KrBK4Q4b4i2e3gpafKy:bf7qwsy)*

**Comment by bloody76** [comment]
lgtm ? :P

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/44#-:-KrBW9gmFn5gDqrZePZw:b-azqe5e)*

**Comment by nitnelave** [comment]
Yes, you have it already :) It's just waiting for travis

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/44#-:-KrBXw_fBkDa7GTUfndy:bpn8gqv)*

**Comment by bloody76** [comment]
han, didn't see :D

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/44#-:-KrB_aDx0shnDUDc2gVt:b-xi7tu1)*

**Pull request merged**
