### PR TITLE
Add some codegen code for the if else statements

### PR DESCRIPTION
**Pull request by bloody76**
This change is [Reviewable](https://reviewable.io/reviews/nitnelave/hopper/55)

### CODE REVIEW

**Comment by bloody76** [comment]
Reviewed 27 of 27 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/55)*

**Comment by nitnelave** [comment]
Review status: 27 of 28 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/ast/if_statement.h, line 23 at r2](https://reviewable.io:443/reviews/nitnelave/hopper/55#-KrVPWo5GGd1fJclebjC:-KrVPWo5GGd1fJclebjD:b-ev6690) ([raw file](https://github.com/nitnelave/hopper/blob/79dc09c7675926cf50aae6c070f1128ed25e8245/src/ast/if_statement.h#L23)):*
> ```objc
>         bodies_(std::move(bodies)),
>         else_statement_(std::move(else_statement)) {
>     assert(conditions.size() == bodies.size());
> ```

vector<pair<condition, body>>?

---

*[src/codegen/codegen.cc, line 42 at r2](https://reviewable.io:443/reviews/nitnelave/hopper/55#-KrV6aaFzTXnVefesKdK:-KrV6aaFzTXnVefesKdL:b-tcstrw) ([raw file](https://github.com/nitnelave/hopper/blob/79dc09c7675926cf50aae6c070f1128ed25e8245/src/codegen/codegen.cc#L42)):*
> ```cpp
>     : module_(std::make_unique<Module>(name, context_)),
>       ir_builder_(context_, ConstantFolder()),
>       current_block_(nullptr) {
> ```

No, I don't want any nullptr. If you want a nullable pointer, make it an `Option<pointer>` and set it to `none`

---

*[src/codegen/codegen.h, line 58 at r2](https://reviewable.io:443/reviews/nitnelave/hopper/55#-KrVOrCWYMh8Oh2h2_Hc:-KrVOrCWYMh8Oh2h2_Hd:bbemrat) ([raw file](https://github.com/nitnelave/hopper/blob/79dc09c7675926cf50aae6c070f1128ed25e8245/src/codegen/codegen.h#L58)):*
> ```objc
>   // Return value of visitation of a value node.
>   llvm::Value* gen_value_;
>   llvm::BasicBlock* current_block_;
> ```

Documentation

---

*[src/codegen/codegen.h, line 62 at r2](https://reviewable.io:443/reviews/nitnelave/hopper/55#-KrVQMSN9XHUbEE0xStf:-KrVQMSN9XHUbEE0xStg:b-hrqrwr) ([raw file](https://github.com/nitnelave/hopper/blob/79dc09c7675926cf50aae6c070f1128ed25e8245/src/codegen/codegen.h#L62)):*
> ```objc
>   std::string current_function_name_;
> 
>   bool return_unhandled_ = false;
> ```

return_handled, it's better to have positive names/concepts.

---

*[src/codegen/codegen.h, line 65 at r2](https://reviewable.io:443/reviews/nitnelave/hopper/55#-KrVQ2bUjuPDBT55vpTl:-KrVQ2bUjuPDBT55vpTm:b-c711t9) ([raw file](https://github.com/nitnelave/hopper/blob/79dc09c7675926cf50aae6c070f1128ed25e8245/src/codegen/codegen.h#L65)):*
> ```objc
> };
> 
> #define CONSUME_UNHANDLED_RETURN(VAR) \
> ```

I'm not a fan of that macro... If you really want to use a one-liner to replace a two-liner, write something like:
`auto was_handled = consume_unhandled_return(&return_unhandled_);`

---

*[src/codegen/codegen_statement.cc, line 27 at r2](https://reviewable.io:443/reviews/nitnelave/hopper/55#-KrVOzcGn4IZUu58vvjd:-KrVOzcGn4IZUu58vvje:b-g4dwwm) ([raw file](https://github.com/nitnelave/hopper/blob/79dc09c7675926cf50aae6c070f1128ed25e8245/src/codegen/codegen_statement.cc#L27)):*
> ```cpp
> 
>     if (return_unhandled_) {
>       return;
> ```

Add a warning to the error list if it's not the last statement.

---

*[src/codegen/codegen_statement.cc, line 35 at r2](https://reviewable.io:443/reviews/nitnelave/hopper/55#-KrVPiMj3L6uzH6YmHuz:-KrVPiMj3L6uzH6YmHv-:b3gcad9) ([raw file](https://github.com/nitnelave/hopper/blob/79dc09c7675926cf50aae6c070f1128ed25e8245/src/codegen/codegen_statement.cc#L35)):*
> ```cpp
>   if (node->value().is_ok()) {
>     node->value().value_or_die()->accept(*this);
>     assert(gen_value_ != nullptr && "No value generated by the visitor");
> ```

turn gen_value_ into an Option to remove nullptr

---

*[src/codegen/codegen_statement.cc, line 57 at r2](https://reviewable.io:443/reviews/nitnelave/hopper/55#-KrVPG8QPfyp64mvscC3:-KrVPG8RloOznUOQclpX:b-weswee) ([raw file](https://github.com/nitnelave/hopper/blob/79dc09c7675926cf50aae6c070f1128ed25e8245/src/codegen/codegen_statement.cc#L57)):*
> ```cpp
> 
>   // We generate the first block of code for the 'if' statement.
>   (*condition++)->accept(*this);
> ```

Separate the increment from the usage.

---

*[src/codegen/codegen_statement.cc, line 67 at r2](https://reviewable.io:443/reviews/nitnelave/hopper/55#-KrVQo3GJPpbFEDR3SZ9:-KrVQo3GJPpbFEDR3SZA:b-i0zrbu) ([raw file](https://github.com/nitnelave/hopper/blob/79dc09c7675926cf50aae6c070f1128ed25e8245/src/codegen/codegen_statement.cc#L67)):*
> ```cpp
>   BasicBlock* last_block = current_block_;
>   BasicBlock* jump_block = current_block;
>   while (condition != std::end(node->conditions())) {
> ```

I'll have a closer look at the implementation later, but I'd really like to see the binary (non-vector) one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/55)*

**Comment by bloody76** [comment]
Reviewed 1 of 1 files at r3, 2 of 30 files at r4, 31 of 31 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/55)*

**Comment by bloody76** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/ast/if_statement.h, line 23 at r2](https://reviewable.io:443/reviews/nitnelave/hopper/55#-KrVPWo5GGd1fJclebjC:-KrXc4zn6qXgc4apJVAe:b9eqo5u) ([raw file](https://github.com/nitnelave/hopper/blob/79dc09c7675926cf50aae6c070f1128ed25e8245/src/ast/if_statement.h#L23)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

vector<pair<condition, body>>?
</blockquote></details>

modified in the new recursive version

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/55)*

**Comment by bloody76** [comment]
Review status: 29 of 32 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/codegen/codegen.cc, line 42 at r2](https://reviewable.io:443/reviews/nitnelave/hopper/55#-KrV6aaFzTXnVefesKdK:-KrXl4MiP6HKaaT5cumL:b-896fix) ([raw file](https://github.com/nitnelave/hopper/blob/79dc09c7675926cf50aae6c070f1128ed25e8245/src/codegen/codegen.cc#L42)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

No, I don't want any nullptr. If you want a nullable pointer, make it an `Option<pointer>` and set it to `none`
</blockquote></details>

Done.

---

*[src/codegen/codegen.h, line 58 at r2](https://reviewable.io:443/reviews/nitnelave/hopper/55#-KrVOrCWYMh8Oh2h2_Hc:-KrXl5IxiYft-b91FeQc:b-896fix) ([raw file](https://github.com/nitnelave/hopper/blob/79dc09c7675926cf50aae6c070f1128ed25e8245/src/codegen/codegen.h#L58)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

Documentation
</blockquote></details>

Done.

---

*[src/codegen/codegen.h, line 62 at r2](https://reviewable.io:443/reviews/nitnelave/hopper/55#-KrVQMSN9XHUbEE0xStf:-KrXl5d2hxGaiLXjxoda:b-896fix) ([raw file](https://github.com/nitnelave/hopper/blob/79dc09c7675926cf50aae6c070f1128ed25e8245/src/codegen/codegen.h#L62)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

return_handled, it's better to have positive names/concepts.
</blockquote></details>

Done.

---

*[src/codegen/codegen.h, line 65 at r2](https://reviewable.io:443/reviews/nitnelave/hopper/55#-KrVQ2bUjuPDBT55vpTl:-KrXl6dv6zXsPb27H8P6:b-896fix) ([raw file](https://github.com/nitnelave/hopper/blob/79dc09c7675926cf50aae6c070f1128ed25e8245/src/codegen/codegen.h#L65)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

I'm not a fan of that macro... If you really want to use a one-liner to replace a two-liner, write something like:
`auto was_handled = consume_unhandled_return(&return_unhandled_);`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/55)*

**Comment by bloody76** [comment]
Review status: 29 of 32 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/codegen/codegen_statement.cc, line 27 at r2](https://reviewable.io:443/reviews/nitnelave/hopper/55#-KrVOzcGn4IZUu58vvjd:-KrXpLYLLp_vsDKS1gpR:b-896fix) ([raw file](https://github.com/nitnelave/hopper/blob/79dc09c7675926cf50aae6c070f1128ed25e8245/src/codegen/codegen_statement.cc#L27)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

Add a warning to the error list if it's not the last statement.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/55)*

**Comment by bloody76** [comment]
Review status: 28 of 33 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/codegen/codegen_statement.cc, line 35 at r2](https://reviewable.io:443/reviews/nitnelave/hopper/55#-KrVPiMj3L6uzH6YmHuz:-KrXq40P2Xmd2pfWsHtT:b-896fix) ([raw file](https://github.com/nitnelave/hopper/blob/79dc09c7675926cf50aae6c070f1128ed25e8245/src/codegen/codegen_statement.cc#L35)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

turn gen_value_ into an Option to remove nullptr
</blockquote></details>

Done.

---

*[src/codegen/codegen_statement.cc, line 57 at r2](https://reviewable.io:443/reviews/nitnelave/hopper/55#-KrVPG8QPfyp64mvscC3:-KrXq78-sc7a7-JRkx8A:bg03zps) ([raw file](https://github.com/nitnelave/hopper/blob/79dc09c7675926cf50aae6c070f1128ed25e8245/src/codegen/codegen_statement.cc#L57)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

Separate the increment from the usage.
</blockquote></details>

I think this is deprecated with the recursive version

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/55)*

**Comment by bloody76** [comment]
Reviewed 1 of 6 files at r6.
Review status: 29 of 33 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/55)*

**Comment by bloody76** [comment]
Reviewed 3 of 6 files at r6.
Review status: 32 of 33 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/55)*

**Comment by bloody76** [comment]
Reviewed 1 of 6 files at r6.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/55)*

**Comment by nitnelave** [comment]
Check the coverage, to see which part you didn't test sufficiently.

---

Reviewed 5 of 31 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/codegen/codegen.h, line 86 at r6](https://reviewable.io:443/reviews/nitnelave/hopper/55#-KrZzuLErZC1A7-xicRq:-KrZzuLErZC1A7-xicRr:b20cb1m) ([raw file](https://github.com/nitnelave/hopper/blob/07299a4bfdbce6dd01d75be7e495dafdffadd477/src/codegen/codegen.h#L86)):*
> ```objc
>   bool has_returned_ = false;
> 
>   std::list<CodeGenWarning> warning_messages_;
> ```

Use an `ErrorList` from src/visitor/error_visitor.h

---

*[src/codegen/codegen_statement.cc, line 25 at r6](https://reviewable.io:443/reviews/nitnelave/hopper/55#-Kr_HP4GxtjwWD2JGTuY:-Kr_HP4GxtjwWD2JGTuZ:b4zdo53) ([raw file](https://github.com/nitnelave/hopper/blob/07299a4bfdbce6dd01d75be7e495dafdffadd477/src/codegen/codegen_statement.cc#L25)):*
> ```cpp
>     if (already_returned) {
>       warning_messages_.push_back(
>           CodeGenWarning("The statement won't be executed because the function "
> ```

Maybe a message more like "Unreachable code"? And also break after the first warning, or you'll print it for each statement.

---

*[src/codegen/codegen_statement.cc, line 84 at r6](https://reviewable.io:443/reviews/nitnelave/hopper/55#-Kr_K-7OQ1MqoRPHZngH:-Kr_K-7OQ1MqoRPHZngI:bgqepds) ([raw file](https://github.com/nitnelave/hopper/blob/07299a4bfdbce6dd01d75be7e495dafdffadd477/src/codegen/codegen_statement.cc#L84)):*
> ```cpp
>   has_returned_ = if_or_elseif_returned || else_only_returned;
> 
>   if (!has_returned_) {
> ```

This part needs a bit more explanation on when you create the end block or not.

---

*[src/error/error.h, line 169 at r6](https://reviewable.io:443/reviews/nitnelave/hopper/55#-Kr_K5qIfEzj5_I_rqxx:-Kr_K5qIfEzj5_I_rqxy:b1le2ca) ([raw file](https://github.com/nitnelave/hopper/blob/07299a4bfdbce6dd01d75be7e495dafdffadd477/src/error/error.h#L169)):*
> ```objc
>   MaybeError(  // NOLINT: explicit
>       E&& value, typename std::enable_if<
>                      std::is_constructible<Err, E&&>::value>::type* /*unused*/
> ```

can you get rid of the whitespace changes?

---

*[src/parser/parser.cc, line 279 at r6](https://reviewable.io:443/reviews/nitnelave/hopper/55#-Kr_KCa7Q6Cnfop3Ush3:-Kr_KCa7Q6Cnfop3Ush4:b-cx4plc) ([raw file](https://github.com/nitnelave/hopper/blob/07299a4bfdbce6dd01d75be7e495dafdffadd477/src/parser/parser.cc#L279)):*
> ```cpp
>       RETURN_OR_MOVE(auto else_body, parse_statement_or_list());
>       else_statement = std::make_unique<ast::IfStatement>(
>           location.range(), none, std::move(else_body), none);
> ```

Why the location change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/55#-:-Kr_KYpM9pOE2BgPz0Dc:b-v1wyko)*

**Comment by bloody76** [comment]
Reviewed 3 of 3 files at r7.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/codegen/codegen.h, line 86 at r6](https://reviewable.io:443/reviews/nitnelave/hopper/55#-KrZzuLErZC1A7-xicRq:-Kr_T_wY8hYzmmdI5Zvn:b-896fix) ([raw file](https://github.com/nitnelave/hopper/blob/07299a4bfdbce6dd01d75be7e495dafdffadd477/src/codegen/codegen.h#L86)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

Use an `ErrorList` from src/visitor/error_visitor.h
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/55)*

**Comment by bloody76** [comment]
Review status: 30 of 35 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/codegen/codegen_statement.cc, line 25 at r6](https://reviewable.io:443/reviews/nitnelave/hopper/55#-Kr_HP4GxtjwWD2JGTuY:-Kr_TzUynt9Jst22WBVx:b-896fix) ([raw file](https://github.com/nitnelave/hopper/blob/07299a4bfdbce6dd01d75be7e495dafdffadd477/src/codegen/codegen_statement.cc#L25)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

Maybe a message more like "Unreachable code"? And also break after the first warning, or you'll print it for each statement.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/55)*

**Comment by bloody76** [comment]
Review status: 30 of 35 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/error/error.h, line 169 at r6](https://reviewable.io:443/reviews/nitnelave/hopper/55#-Kr_K5qIfEzj5_I_rqxx:-Kr_UYN4JbLT4Vk90wyu:b-896fix) ([raw file](https://github.com/nitnelave/hopper/blob/07299a4bfdbce6dd01d75be7e495dafdffadd477/src/error/error.h#L169)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

can you get rid of the whitespace changes?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/55)*

**Comment by bloody76** [comment]
Review status: 28 of 34 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/parser/parser.cc, line 279 at r6](https://reviewable.io:443/reviews/nitnelave/hopper/55#-Kr_KCa7Q6Cnfop3Ush3:-Kr_V-UbkU1PgrZBqr1g:bosfjb) ([raw file](https://github.com/nitnelave/hopper/blob/07299a4bfdbce6dd01d75be7e495dafdffadd477/src/parser/parser.cc#L279)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

Why the location change?
</blockquote></details>

No reason, I just moved it by accident during the refacto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/55)*

**Comment by bloody76** [comment]
Review status: 28 of 34 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/codegen/codegen_statement.cc, line 84 at r6](https://reviewable.io:443/reviews/nitnelave/hopper/55#-Kr_K-7OQ1MqoRPHZngH:-Kr_VtoGEguGNPvvy_xa:b-896fix) ([raw file](https://github.com/nitnelave/hopper/blob/07299a4bfdbce6dd01d75be7e495dafdffadd477/src/codegen/codegen_statement.cc#L84)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

This part needs a bit more explanation on when you create the end block or not.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/55)*

**Comment by bloody76** [comment]
Reviewed 6 of 7 files at r8.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/55)*

**Comment by bloody76** [comment]
Reviewed 1 of 7 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/55)*

**Comment by nitnelave** [comment]
Reviewed 2 of 30 files at r4, 21 of 31 files at r5, 2 of 6 files at r6, 1 of 3 files at r7, 5 of 7 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/parser/parser.cc, line 3 at r9](https://reviewable.io:443/reviews/nitnelave/hopper/55#-Kr_nIqIqR8Loma2Cwo0:-Kr_nIqJSUZsHgwF9Sje:b-ni6cmi) ([raw file](https://github.com/nitnelave/hopper/blob/2efd9dd2fdc336ad1737df0fa90b9fa9f09e6f1d/src/parser/parser.cc#L3)):*
> ```cpp
> #include "parser/parser.h"
> 
> #include <iostream>
> ```

Remove this header.

---

*[test/resources/resources.cc, line 270 at r9](https://reviewable.io:443/reviews/nitnelave/hopper/55#-Kr_oAOd2C8wkfOYGccD:-Kr_oAOd2C8wkfOYGccE:baebks5) ([raw file](https://github.com/nitnelave/hopper/blob/2efd9dd2fdc336ad1737df0fa90b9fa9f09e6f1d/test/resources/resources.cc#L270)):*
> ```cpp
>   result.value_or_die()->accept(generator);
> 
>   if (!generator.error_list().warnings().empty()) {
> ```

Ideally we would differentiate errors and warnings... it's okay for now, but :/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/55)*

**Comment by bloody76** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[test/resources/resources.cc, line 270 at r9](https://reviewable.io:443/reviews/nitnelave/hopper/55#-Kr_oAOd2C8wkfOYGccD:-Kr_txpXqwQQoGlwCezr:bz5i519) ([raw file](https://github.com/nitnelave/hopper/blob/2efd9dd2fdc336ad1737df0fa90b9fa9f09e6f1d/test/resources/resources.cc#L270)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

Ideally we would differentiate errors and warnings... it's okay for now, but :/
</blockquote></details>

We can change the name form error_list to msg_list if you want. Holding both errors and warnings in the same structure is not really an issue

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/55)*

**Comment by nitnelave** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/resources/resources.cc, line 270 at r9](https://reviewable.io:443/reviews/nitnelave/hopper/55#-Kr_oAOd2C8wkfOYGccD:-Kr_vRAe5HHgYByQwGcK:b-ks8tnw) ([raw file](https://github.com/nitnelave/hopper/blob/2efd9dd2fdc336ad1737df0fa90b9fa9f09e6f1d/test/resources/resources.cc#L270)):*
<details><summary><i>Previously, bloody76 (Bd76) wrote…</i></summary><blockquote>

We can change the name form error_list to msg_list if you want. Holding both errors and warnings in the same structure is not really an issue
</blockquote></details>

No, but in the test, it's tested as `ERROR`, where it should be tested as `WARNING`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/55)*

**Comment by nitnelave** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[test/resources/ir/function_with_consecutive_returns.gh, line 3 at r9](https://reviewable.io:443/reviews/nitnelave/hopper/55#-Kr_vaOcK6GFtlmQB2uu:-Kr_vaOcK6GFtlmQB2uv:b2fuqvk) ([raw file](https://github.com/nitnelave/hopper/blob/2efd9dd2fdc336ad1737df0fa90b9fa9f09e6f1d/test/resources/ir/function_with_consecutive_returns.gh#L3)):*
> ```
> fun main() {
>   return 1;
>   return 2;
> ```

Add another test with another statement after that, I want to check that the message doesn't appear twice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/55)*

**Comment by bloody76** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[test/resources/resources.cc, line 270 at r9](https://reviewable.io:443/reviews/nitnelave/hopper/55#-Kr_oAOd2C8wkfOYGccD:-Kr_vd6NNWP1t5iw-MqV:b-y539xe) ([raw file](https://github.com/nitnelave/hopper/blob/2efd9dd2fdc336ad1737df0fa90b9fa9f09e6f1d/test/resources/resources.cc#L270)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

No, but in the test, it's tested as `ERROR`, where it should be tested as `WARNING`
</blockquote></details>

Han ok, yes indeed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/55)*

**Comment by bloody76** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/parser/parser.cc, line 3 at r9](https://reviewable.io:443/reviews/nitnelave/hopper/55#-Kr_nIqIqR8Loma2Cwo0:-KrabvQkh7GL1T3T0E2X:b-896fix) ([raw file](https://github.com/nitnelave/hopper/blob/2efd9dd2fdc336ad1737df0fa90b9fa9f09e6f1d/src/parser/parser.cc#L3)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

Remove this header.
</blockquote></details>

Done.

---

*[test/resources/ir/function_with_consecutive_returns.gh, line 3 at r9](https://reviewable.io:443/reviews/nitnelave/hopper/55#-Kr_vaOcK6GFtlmQB2uu:-KracIJhUjn7b7QW1NE0:b-896fix) ([raw file](https://github.com/nitnelave/hopper/blob/2efd9dd2fdc336ad1737df0fa90b9fa9f09e6f1d/test/resources/ir/function_with_consecutive_returns.gh#L3)):*
<details><summary><i>Previously, nitnelave (nitnelave) wrote…</i></summary><blockquote>

Add another test with another statement after that, I want to check that the message doesn't appear twice.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/55)*

**Comment by bloody76** [comment]
Reviewed 1 of 2 files at r10.
Review status: 34 of 35 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/55)*

**Comment by bloody76** [comment]
Reviewed 1 of 2 files at r10.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/55)*

**Comment by nitnelave** [comment]
:lgtm:

---

Reviewed 1 of 7 files at r8, 1 of 2 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nitnelave/hopper/55#-:-Krb-GwLUxABniJS8wJP:bnfp4nl)*

**Pull request merged**
